#+TAGS: notes
#+AUTHOR: Guanghui Qu
#+STARTUP: overview, for taking some random notes
#+LATEX_HEADER: \usepackage{xltxtra}
#+LATEX_HEADER: \setmainfont{FangSong}
#+LATEX_HEADER: \usepackage{seqsplit}

* Random notes

** Self brief introduction
  Hello, everyone. Today I want to talk about org mode. So what is org mode? Org mode is a outline processor within emacs.
 Org mode is for keeping notes, maintaining TODO lists, planning projects, and authoring documents with a fast and effective plain-text system.
With a emacs version greater than 23, org mode is already a build-in package. It provides a rich set of markup language. We can use lists, links, headlines, tables to manage our contents.
We can also export all of my org files to pdf , plain text or latex files with just a few key strokes. Org mode can even help me to manage my agenda.
It's also my personal wiki system . I came across emacs org mode a few months ago, but I really love it now. It's awesome! It really deserves the time to learn.

** How to learn a new language?
Find a project you are familiar with and reimplement it with the new language. After finish it, review the project to see the difference between the new language and the languages you used to using.

** Find the target
*** What you can be the best in the world at?
Instructors( have some confidence)
 best game client programmer(have some confidence)
 best game server programmer?
best vim user?(have a lot confidence, but still need more)
 best emacs user?(a little confidence)
best c++ programmer?
*** What drives your "economic" engine.
Writing articles. (I have the ability to write well)
Develop games.( I am good at iterate something to make it better)
Teatch others to learn game programming.
*** What you are deeply passionate about.
Learning useful stuff which can boost my productivity.(like ruby in web and go in server)
Learning anything new about vim.( speed up my programming speed)
Learing  anything new about emacs.(management my personal life)
Let game programming is not a secret any more.(I love to share some new)


